### ISSUE TITLE
Shader Effects Issue (Also affects dash orbs)

### ISSUE THREAD

**Issue by RikuNova** [shadowforce78/Rainbow-Icon#3]
Shader effects that directly affect the player turns the icon white. This only happens if the preset setting is either only on one player color or only glow. This is showcased in Dash with the first spider having a shader on the player.

Icon before going through the first spider. (No shaders that affect the player yet. Glow only enabled.)
![20240301165016_1](https://github.com/shadowforce78/Rainbow-Icon/assets/96581417/8078e701-2b21-4f33-aa9b-0f413dbbc796)

Icon after going through the first spider. (Icon is now completely white after the shader turns off.)
![20240301165025_1](https://github.com/shadowforce78/Rainbow-Icon/assets/96581417/82c893e0-1443-4900-848c-70554ce0fa3e)

Ditto but using one player color only.
![20240301164957_1](https://github.com/shadowforce78/Rainbow-Icon/assets/96581417/4d6b54cd-1e35-4beb-8cd6-f83fd07c7c0b)

**Comment by shadowforce78** [comment]
Im working on it

**Comment by shadowforce78** [comment]
This bug was caused by the flash of the spider effect, its know fixed for 1.0.5
