### ISSUE TITLE
Suggestion : Revamped Options & More Color Choices

### ISSUE THREAD

**Issue by RikuNova** [shadowforce78/Rainbow-Icon#4]
I love how presets for P1, P2, Glow, and Everything have been added. However, I want to give a suggestion on being able to select the player's Wave Trail as a separate option, and maybe (if possible) even the progress bar during gameplay! With these new options in mind, I also feel like choosing what you want enabled shouldn't be a slider preset, but instead being toggleable boxes.

**Comment by shadowforce78** [comment]
For the wave trail seperated option, its done for the next update.
I can also make the progress bar, but it will cause problem with some other mod that already modifying the progress bar.
Also I changed the preset select type to only button, slider was not that good

**Comment by RikuNova** [comment]
What is the specific mod that modifies the progress bar? I'm quite curious now.

**Comment by shadowforce78** [comment]
I made one called "progress bar edit"
But geode didnt accept it for the moment so maybe I will ad the rainbow features here

**Comment by shadowforce78** [comment]
For the update 1.0.4 I added the progress bar so it now can be rainbow too I hope you will like it, also I hope I will not have issues with others mod
