### ISSUE TITLE
Spider bug with rainbow glow.

### ISSUE THREAD

**Issue by MaximoLiner** [shadowforce78/Rainbow-Icon#5]
https://github.com/shadowforce78/Rainbow-Icon/assets/125593074/e8d2d0d5-5992-425e-92d3-d23f924caf15

version: latest (1.0.4)

version of GD: Steam 2.204

**Comment by shadowforce78** [comment]
I already heard about this bug, im trying to fix it for 1.0.5
This only happen if you choose preset 2 or 3 and disable glow
Sorry for this

**Comment by MaximoLiner** [comment]
:sadge:
It's fine, I can wait for the gay glow

**Comment by shadowforce78** [comment]
This bug is know fixed for 1.0.5

**Comment by RadiantHexagon** [comment]
It seems as if the same is happening with dash orbs

**Comment by RadiantHexagon** [comment]
Stills happens with me for rainbow glow :/
