### ISSUE TITLE
game crashes upon pausing in a level

### ISSUE THREAD

**Issue by Master3499** [shadowforce78/Rainbow-Icon#6]
[2024-03-07_14-43-03.log](https://github.com/shadowforce78/Rainbow-Icon/files/14529857/2024-03-07_14-43-03.log)

Here is the crash report made by Geode. The game crashes as soon as I press escape to open the pause menu, not even showing the menu, just freezing then crashing.

Edit: I just tried it again with only RainbowIcon activated in Geode, and the same thing happened.

**Comment by shadowforce78** [comment]
Please send me a screen of the settings you enabled
Also send me the version of the mod you are using rn

**Comment by Master3499** [comment]
I'm using ver 1.0.5, but the same thing was happening on 1.0.4 as well.

These are the setting I have (assuming this is what you mean)
![Untitled](https://github.com/shadowforce78/Rainbow-Icon/assets/162635477/c5b0fb8c-73ff-4ccf-bb3e-d43a0f018be6)

Edit: I tried it again using all the default settings for the mod, and the same thing happens, the game instantly closes the moment I press escape while in a level (I just did stereo madness)

**Comment by shadowforce78** [comment]
I cant simulate the crash, what are you playing on ?
Android or Windows

**Comment by shadowforce78** [comment]
F*ck I didn't want to close it

**Comment by shadowforce78** [comment]
Also, join the discord for a faster answer : https://discord.com/invite/zC4naZG8Bx

**Comment by shadowforce78** [comment]
Node ID 👍
