### ISSUE TITLE
Glow doesnt work

### ISSUE THREAD

**Issue by REBELSPARK279** [shadowforce78/Rainbow-Icon#7]
On android here and the glow doesnt do the rainbow effect. I have it on preset 0 and glow rainbow enabled.

https://github.com/shadowforce78/Rainbow-Icon/assets/130930743/f82edc35-18c5-475c-a8ef-fd91423e170f

**Comment by shadowforce78** [comment]
Does the glow work if you set another preset ?

**Comment by REBELSPARK279** [comment]
Nope it doesnt

**Comment by shadowforce78** [comment]
try disabling blending glow if you have it, its breaking glow system

**Comment by REBELSPARK279** [comment]
Works now but it worked with blending glow in eariler versions

**Comment by shadowforce78** [comment]
I had to change how to glow system work because it was breaking on macOS
