### ISSUE TITLE
Separate dual icons and Rainbow Icon

### ISSUE THREAD

**Issue by Pizider** [shadowforce78/Rainbow-Icon#8]
Hi! On Geometry Dash I received a "warning" because the Rainbow Icon mod and the Separate Dual Icons mod **aren't compatible** and the Rainbow Icon doesn't apply to the Separate Dual Icons, can you please make an update where the Rainbow Icon can be applied to the Separate Dual Icon?

**Comment by shadowforce78** [comment]
For the moment its not possible, but I will work on this later, for the moment I have other features to add
